apiVersion: apps/v1
kind: Deployment
metadata:
    name: deployment-transaction
    labels:
        app: myapp-pix-grupo3-transaction
spec:
    template:
        metadata:
            name: customer-pix-grupo3
            labels:
                app: myapp-pix-grupo3-transaction
        spec:
            containers:
                - name: pix-grupo3-transaction-container
                  image: registry-itau.mastertech.com.br/pix-grupo3-transaction
            imagePullSecrets:
                - name: regcred
    replicas: 2
    selector:
        matchLabels:
            app: myapp-pix-grupo3-transaction
