apiVersion: apps/v1
kind: Deployment
metadata:
    name: deployment-contacts
    labels:
        app: myapp-pix-grupo3-contacts
spec:
    template:
        metadata:
            name: costumer-pix-grupo3
            labels:
                app: myapp-pix-grupo3-contacts
        spec:
            containers:
                - name: pix-grupo3-contacts-container
                  image: registry-itau.mastertech.com.br/pix-grupo3-contacts
            imagePullSecrets:
                - name: regcred
    replicas: 2
    selector:
        matchLabels:
            app: myapp-pix-grupo3-contacts
