apiVersion: v1
kind: Service
metadata:
  labels:
    app: myapp-pix-grupo3-eureka
  name: myapp-pix-grupo3-eureka 
spec:
  ports:
  - port: 8761
    targetPort: 8761
  selector:
    app: myapp-pix-grupo3-eureka
  type: NodePort
