apiVersion: v1
kind: Service
metadata:
  labels:
    app: myapp-pix-grupo3-transaction
  name: myapp-pix-grupo3-transaction 
spec:
  ports:
  - port: 8083
    targetPort: 8083
    name: myapp-pix-grupo3-transaction
  selector:
    app: myapp-pix-grupo3-transaction
  type: NodePort
