apiVersion: v1
kind: Service
metadata:
  labels:
    app: myapp-pix-grupo3-contacts
  name: myapp-pix-grupo3-contacts 
spec:
  ports:
  - port: 8082
    targetPort: 8082
    name: myapp-pix-grupo3-contacts
  selector:
    app: myapp-pix-grupo3-contacts
  type: NodePort
