apiVersion: v1
kind: Service
metadata:
  labels:
    app: myapp-pix-grupo3-customer
  name: myapp-pix-grupo3-customer 
spec:
  ports:
  - port: 8081
    targetPort: 8081
    name: myapp-pix-grupo3-customer
  selector:
    app: myapp-pix-grupo3-customer
  type: NodePort
