apiVersion: v1
kind: Service
metadata:
  labels:
    app: myapp-pix-grupo3-notification
  name: myapp-pix-grupo3-notification
spec:
  ports:
    - port: 8097
      targetPort: 8097
      name: myapp-pix-grupo3-notification
  selector:
    app: myapp-pix-grupo3-notification
  type: NodePort
