apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-bond
  labels:
    app: myapp-pix-grupo3-bond
spec:
  template:
    metadata:
      name: bond-pix-grupo3
      labels:
        app: myapp-pix-grupo3-bond
    spec:
      containers:
        - name: myapp-pix-grupo3-bond-container
          image: registry-itau.mastertech.com.br/pix-grupo3-bond
      imagePullSecrets:
        - name: regcred
  replicas: 2
  selector:
    matchLabels:
      app: myapp-pix-grupo3-bond

